### ISSUE TITLE
keys_to_be_pressed doesn't seem to work

### ISSUE THREAD

**Issue by tacotexmex** [DS-Minetest/keyevent#1]
I put "sneak" as value for keys_to_be_pressed but nothing happens when I do. Key check by my own code works.

**Comment by Desour** [comment]
O_o Someone uses this mod…

This is my fault.
I forgot to add a `keys` parameter here:
https://github.com/DS-Minetest/keyevent/blob/6ad4ecfbaac9e49b695bf2749d5828ebc804d59a/init.lua#L123

I will fix this.

Hopefully this had no reason.

**Comment by Desour** [comment]
Done: https://github.com/DS-Minetest/keyevent/commit/00e4ba5b14c5ad7767babecd108ce2ccbaa8f856

Note that I didn't test.

**Comment by tacotexmex** [comment]
> O_o Someone uses this mod…

Of course, it’s great! I love that it provides two ways of reading the keys: the novel way (returns table) and the technical way (returns bit).

**Comment by Desour** [comment]
Did the change help?

**Comment by tacotexmex** [comment]
I’ll check soon.

Btw, is using keys_to_be_pressed more performant in any way?

**Comment by Desour** [comment]
It depends on how you check whether you do something on the callback, I guess.

This mod is old, lacking in documentation and not perfect.

**Comment by tacotexmex** [comment]
But not in and of itself then? And it’s not like it’s ”cheaper” to use the bits function, is it?

Regardless, it’s the best mod of its kind and even I managed to figure out how it worked so writing docs shouldn’t be too tedious.

Only thing I can think of to add would be to add on_hold and on_release functions as well but these would be merely for ease of use since both can be achieved with the existing functions.

**Comment by Desour** [comment]
Thanks for the compliments!

I think, it's not more efficient to use the bits function as the table is always created ([see here](https://github.com/DS-Minetest/keyevent/blob/00e4ba5b14c5ad7767babecd108ce2ccbaa8f856/init.lua#L138)).
>But not in and of itself then?

¿¿??
The code tells more about its cheapness than I can.

You can of course make a PR, that would be super nice. (Thanks for creating the issue btw.. I would never have found the problem out myself without using this mod.)
