### ISSUE TITLE
Can only register one keyevent

### ISSUE THREAD

**Issue by tacotexmex** [DS-Minetest/keyevent#2]
I'm registering keyevent like so:
```
keyevent.register_on_keypress(function(keys, old_keys, dtime, player_name)
	local player = minetest.get_player_by_name(player_name)
	if keys.sneak then
	  --stuff
	elseif old_keys and old_keys.sneak then
          --other stuff
	end
end)
```

Only the _last_ registered keyevent works. Am I doing something wrong here?

**Comment by Desour** [comment]
This has the same reason as #1, ergo I'll merge both issues into one.

**Comment by tacotexmex** [comment]
Hello, this is still an issue. Using this code for testing, the chat only signals from 2 and 4:

```
keyevent.register_on_keypress(function(keys, old_keys, dtime, player_name)
	minetest.chat_send_all("Hello from mod 1")
end)

keyevent.register_on_keypress(function(keys, old_keys, dtime, player_name)
	minetest.chat_send_all("Hello from mod 2")
end)

keyevent.register_on_keypress_bits(function(keys, old_keys, dtime, player_name)
	minetest.chat_send_all("Hello from mod 3")
end)

keyevent.register_on_keypress_bits(function(keys, old_keys, dtime, player_name)
	minetest.chat_send_all("Hello from mod 4")
end)
```

**Comment by Desour** [comment]
Oh, I see, this is a different issue, sorry for closing.

**Comment by Desour** [comment]
Why was I so stupid when I made this mod?
https://github.com/DS-Minetest/keyevent/blob/00e4ba5b14c5ad7767babecd108ce2ccbaa8f856/init.lua#L120

**Comment by tacotexmex** [comment]
Heh. It’s very useful still but soon I’ll need to be able to separate events into different functions, not mash them all together ^_^

**Comment by Desour** [comment]
I've tried to fix this: https://github.com/DS-Minetest/keyevent/commit/8273b4ef44b9573b75957a3e6a9e7d8c02519c10
But it isn't tested.
I'll close this issue when the fix is tested and everything works as it should.

**Comment by tacotexmex** [comment]
Did work!

**Comment by Desour** [comment]
Thanks!

**Comment by tacotexmex** [comment]
No, thank _you_!

**Comment by Desour** [comment]
Testing is more work than rewriting a bit.

**Comment by tacotexmex** [comment]
Yup. I wonder at what scale unit tests are useful…

**Comment by Desour** [comment]
I've actually never made any unittests.

**Comment by tacotexmex** [comment]
Me neither! Like you said, I rather rewrite it. (or like in this case, have users testing it)
