### ISSUE TITLE
Implement mod channel communication

### ISSUE THREAD

**Issue by tacotexmex** [DS-Minetest/keyevent#3]
Even though there's no server-side distribution of CSMs yet, it will eventually be realized and is valuable for development right now.

**Comment by Desour** [comment]
Do you mean that I check for changed keys in a csm and send it via modchannel to a ssm?
This doesn't really make sense. In csm there will be real keyevents from the core which will hopefully replace this. A mod that sends all this events via mod channels can be done later, when it's possible.

**Comment by tacotexmex** [comment]
Alright, I understand.
